
-- CREATE
CREATE TABLE USERS(ID INT auto_increment UNIQUE, USERNAME VARCHAR(100)PRIMARY KEY,ACTIVE BOOLEAN, WORKLOAD INT);

--INSERT
INSERT INTO USERS(USERNAME, ACTIVE, WORKLOAD) VALUES ('Prashanth', true,0);

--SELECT ALL AVAILABLE USERNAME
SELECT USERNAME from USERS;

-- SELECT BY ID
SELECT USERNAME, ACTIVE, WORKLOAD from USERS
where id = 1;

-- SELECT USERS WITH UNASSIGNED TASKS
SELECT  USERNAME, ACTIVE, WORKLOAD from USERS
WHERE WORKLOAD=0;

-- SELECT INACTIVE USERS
SELECT  USERNAME, ACTIVE, WORKLOAD from USERS
WHERE ACTIVE=false;

--UPDATE
UPDATE USERS SET ACTIVE=false WHERE ID=1;

--DELETE using ID
DELETE FROM USERS WHERE ID=1;
--DELETE using USERNAME
DELETE FROM USERS WHERE USERNAME='Prashanth';





